#include "lucy/value.hpp"
#include "lucy/ast.hpp"
#include <iomanip>
#include <sstream>
using namespace lucy;
bool Value::is_number()const{return std::holds_alternative<long long>(data)||std::holds_alternative<double>(data);}
bool Value::is_truthy()const{if(std::holds_alternative<Nil>(data))return false;if(auto p=std::get_if<bool>(&data))return *p;if(auto p=std::get_if<long long>(&data))return *p!=0;if(auto p=std::get_if<double>(&data))return *p!=0.0;if(auto p=std::get_if<std::string>(&data))return !p->empty();if(auto p=std::get_if<ArrayPtr>(&data))return p&&!(*p)->empty();if(auto p=std::get_if<MapPtr>(&data))return p&&!(*p)->empty();return true;}
std::string Value::to_string()const{if(std::holds_alternative<Nil>(data))return "nil";if(auto p=std::get_if<bool>(&data))return *p?"true":"false";if(auto p=std::get_if<long long>(&data))return std::to_string(*p);if(auto p=std::get_if<double>(&data)){std::ostringstream o;o<<std::setprecision(15)<<*p;return o.str();}if(auto p=std::get_if<std::string>(&data))return *p;if(auto p=std::get_if<ArrayPtr>(&data)){std::string r="[";for(size_t i=0;i<(*p)->size();++i){if(i)r+=", ";r+=(*p)->at(i).to_string();}return r+"]";}if(auto p=std::get_if<MapPtr>(&data)){std::string r="{";size_t i=0;for(auto&[k,v]:**p){if(i++)r+=", ";r+=k+": "+v.to_string();}return r+"}";}if(auto p=std::get_if<FunctionPtr>(&data))return "<function "+(*p)->name+">";if(auto p=std::get_if<ClassPtr>(&data))return "<class "+(*p)->name+">";if(auto p=std::get_if<InstancePtr>(&data))return "<"+(*p)->klass->name+" instance>";if(std::holds_alternative<NativePtr>(data))return "<native>";return "<value>";}
std::string Value::type_name()const{if(std::holds_alternative<Nil>(data))return "nil";if(std::holds_alternative<bool>(data))return "bool";if(std::holds_alternative<long long>(data))return "int";if(std::holds_alternative<double>(data))return "double";if(std::holds_alternative<std::string>(data))return "string";if(std::holds_alternative<ArrayPtr>(data))return "array";if(std::holds_alternative<MapPtr>(data))return "map";if(std::holds_alternative<FunctionPtr>(data))return "function";if(std::holds_alternative<ClassPtr>(data))return "class";if(std::holds_alternative<InstancePtr>(data))return "instance";if(std::holds_alternative<NativePtr>(data))return "native";return "instance";}
